# Generated by Django 3.1 on 2020-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('LCTN', 'Location'), ('TM', 'Time')], max_length=6)),
            ],
            options={
                'verbose_name': 'ArrivalTime',
                'verbose_name_plural': 'ArrivalTime',
            },
        ),
    ]
