# Generated by Django 3.1 on 2020-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivaltime', '0002_auto_20200824_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivaltime',
            name='category',
            field=models.CharField(choices=[('LCTN', 'Location'), ('TM', 'Time')], max_length=6),
        ),
    ]
