# Generated by Django 3.1 on 2020-08-24 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departurestime', '0002_auto_20200824_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='departurestime',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departurestime',
            name='clock',
            field=models.CharField(choices=[('T00', '09:00:23Z'), ('T01', '10:00:23Z'), ('T02', '11:00:23Z')], max_length=50),
        ),
        migrations.AlterField(
            model_name='departurestime',
            name='date',
            field=models.CharField(choices=[('A', '2020-06-10'), ('B', '2020-06-11'), ('C', '2020-06-12'), ('D', '2020-06-13'), ('E', '2020-06-14'), ('F', '2020-06-15'), ('G', '2020-06-16')], max_length=50),
        ),
    ]
