# Generated by Django 3.1 on 2020-08-24 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arrivalport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalport',
            name='category',
        ),
        migrations.AddField(
            model_name='arrivalport',
            name='country',
            field=models.CharField(choices=[('SIN', 'Singapore'), ('BKK', 'Thailand'), ('CGK', 'Indonesia'), ('KUL', 'Malaysia'), ('MNL', 'Philippines'), ('SGN', 'Vietnam'), ('BWN', 'Brunei'), ('VTE', 'Laos'), ('RGN', 'Myanmar'), ('PNH', 'Kamboja')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrivalport',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
