# Generated by Django 3.1 on 2020-08-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivalport', '0002_auto_20200824_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalport',
            name='country',
            field=models.CharField(choices=[('SIN', 'Singapore'), ('BKK', 'Thailand'), ('CGK', 'Indonesia'), ('KUL', 'Malaysia'), ('MNL', 'Philippines'), ('SGN', 'Vietnam'), ('BWN', 'Brunei'), ('VTE', 'Laos'), ('RGN', 'Myanmar'), ('PNH', 'Kamboja')], max_length=200),
        ),
    ]
