# Generated by Django 3.1 on 2020-08-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrivalport', '0003_auto_20200824_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivalport',
            old_name='country',
            new_name='county',
        ),
    ]
