# Generated by Django 3.1 on 2020-08-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightsNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(choices=[('SIN', 'Singapore'), ('BKK', 'Thailand'), ('CGK', 'Indonesia'), ('KUL', 'Malaysia'), ('MNL', 'Philippines'), ('SGN', 'Vietnam'), ('BWN', 'Brunei'), ('VTE', 'Laos'), ('RGN', 'Myanmar'), ('PNH', 'Kamboja')], max_length=200)),
            ],
            options={
                'verbose_name': 'FlightsNumber',
                'verbose_name_plural': 'FlightsNumber',
            },
        ),
    ]
