# Generated by Django 3.1 on 2020-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsnumber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsnumber',
            name='number',
            field=models.CharField(choices=[('A', 'QF100'), ('B', 'QF200'), ('C', 'QF300'), ('D', 'QF400'), ('E', 'QF500'), ('F', 'QF600'), ('G', 'QF700'), ('H', 'QF800'), ('I', 'QF900'), ('J', 'QG100'), ('K', 'QG200'), ('L', 'QG300'), ('M', 'QG400'), ('N', 'QG500'), ('O', 'QG600'), ('P', 'QG700'), ('Q', 'QG800'), ('R', 'QG900')], max_length=200),
        ),
    ]
