# Generated by Django 3.1 on 2020-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightnumber', '0002_auto_20200824_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightnumber',
            name='category',
            field=models.CharField(choices=[('C', 'Code'), ('B', 'Boeing')], max_length=6),
        ),
    ]
